"""add_total_registros_to_archivos_excel

Revision ID: acad68a073f7
Revises: fa1084a4f5f7
Create Date: 2025-07-13 20:20:52.238909

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "acad68a073f7"
down_revision: Union[str, None] = "fa1084a4f5f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Agregar la columna como nullable=False con valor por defecto
    op.add_column(
        "ArchivosExcel",
        sa.Column("Total_Registros", sa.Integer(), nullable=False, server_default="0"),
    )

    # Actualizar registros existentes para calcular el Total_Registros
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
        UPDATE ArchivosExcel 
        SET Total_Registros = (
            SELECT COUNT(*) 
            FROM lectura 
            WHERE lectura.ID_Archivo = ArchivosExcel.ID_Archivo
        )
    """
        )
    )

    # Eliminar índices que ya no se necesitan
    op.drop_index("ix_ArchivosExcel_ID_Caso", table_name="ArchivosExcel")
    op.drop_index("ix_archivosexcel_fecha_importacion", table_name="ArchivosExcel")
    op.drop_index("ix_lecturasrelevantes_id_lectura", table_name="LecturasRelevantes")
    op.drop_index("ix_lector_coordenadas", table_name="lector")
    op.drop_index("ix_lector_localidad", table_name="lector")
    op.drop_index("ix_lector_provincia", table_name="lector")
    op.drop_index("ix_lectura_matricula_fecha", table_name="lectura")
    op.drop_index("ix_lectura_tipo_fecha", table_name="lectura")
    op.drop_index("ix_lectura_tipo_fuente", table_name="lectura")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_lectura_tipo_fuente", "lectura", ["Tipo_Fuente"], unique=False)
    op.create_index(
        "ix_lectura_tipo_fecha",
        "lectura",
        ["Tipo_Fuente", "Fecha_y_Hora"],
        unique=False,
    )
    op.create_index(
        "ix_lectura_matricula_fecha",
        "lectura",
        ["Matricula", "Fecha_y_Hora"],
        unique=False,
    )
    op.create_index("ix_lector_provincia", "lector", ["Provincia"], unique=False)
    op.create_index("ix_lector_localidad", "lector", ["Localidad"], unique=False)
    op.create_index(
        "ix_lector_coordenadas",
        "lector",
        ["Coordenada_X", "Coordenada_Y"],
        unique=False,
    )
    op.create_index(
        "ix_lecturasrelevantes_id_lectura",
        "LecturasRelevantes",
        ["ID_Lectura"],
        unique=False,
    )
    op.create_index(
        "ix_archivosexcel_fecha_importacion",
        "ArchivosExcel",
        ["Fecha_de_Importacion"],
        unique=False,
    )
    op.create_index(
        "ix_ArchivosExcel_ID_Caso", "ArchivosExcel", ["ID_Caso"], unique=False
    )
    op.drop_column("ArchivosExcel", "Total_Registros")
    # ### end Alembic commands ###
