"""add_mapas_guardados_table

Revision ID: add_mapas_guardados_2025
Revises: acad68a073f7
Create Date: 2025-01-15 10:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "add_mapas_guardados_2025"
down_revision: Union[str, None] = "acad68a073f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mapas_guardados",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("caso_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("fecha_creacion", sa.DateTime(), nullable=False),
        sa.Column("fecha_modificacion", sa.DateTime(), nullable=False),
        sa.Column("thumbnail", sa.String(length=500), nullable=True),
        sa.Column("estado", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["caso_id"],
            ["Casos.ID_Caso"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mapas_guardados_caso_id"), "mapas_guardados", ["caso_id"], unique=False)
    op.create_index(op.f("ix_mapas_guardados_id"), "mapas_guardados", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mapas_guardados_id"), table_name="mapas_guardados")
    op.drop_index(op.f("ix_mapas_guardados_caso_id"), table_name="mapas_guardados")
    op.drop_table("mapas_guardados")
    # ### end Alembic commands ###
